app/config/routes.rb
Rails.application.routes.draw do
  resources :ayudas
  resources :categories
  resources :galeria
  resources :fotos
  resources :programas
  resources :eventos
  resources :logos
  resources :carrusels
  resources :programas
  resources :nosotros
  resources :noticias
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 
  get "inicio", to: "pages#inicio"
  
  get "nosotros", to: "pages#nosotros"

  get "programas_sociales", to: "pages#programas"

  get "eventos_noticias", to: "pages#eventos_noticias"

  get "como_ayudar", to: "pages#como_ayudar"

  get "fotos_galeria", to: "pages#galeria"
  
  get "factura", to: 'facturas#new', as: 'new_factura'
  
  post "factura", to: 'facturas#create', as: 'create_factura'
  
  get 'contacto', to: 'contactos#new', as: 'new_contacto'
  post 'contacto', to: 'contactos#create', as: 'create_contacto'
  
  root 'pages#inicio'

  devise_for :users, controllers: {
      sessions: 'devise/sessions',
      passwords: 'devise/passwords',
      registrations: 'devise/registrations'
  }

end

app/app/models/programa.rb
class Programa < ApplicationRecord
    has_many :foto, dependent: :destroy
    
    validates :titulo, presence: true
    validates :descripcion, presence: true

end

app/app/controllers/programas_controller.rb
class ProgramasController < ApplicationController
  before_action :set_programa, only: [:show, :edit, :update, :destroy]

  # GET /programas
  # GET /programas.json
  def index
    @programas = Programa.all
  end

  # GET /programas/1
  # GET /programas/1.json
  def show
    @programas = Programa.all
  end

  # GET /programas/new
  def new
    @programa = Programa.new
  end

  # GET /programas/1/edit
  def edit
  end

  # POST /programas
  # POST /programas.json
  def create
    @programa = Programa.new(programa_params)

    respond_to do |format|
      if @programa.save
        format.html { redirect_to @programa, notice: 'Programa was successfully created.' }
        format.json { render :show, status: :created, location: @programa }
      else
        format.html { render :new }
        format.json { render json: @programa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programas/1
  # PATCH/PUT /programas/1.json
  def update
    respond_to do |format|
      if @programa.update(programa_params)
        format.html { redirect_to @programa, notice: 'Programa was successfully updated.' }
        format.json { render :show, status: :ok, location: @programa }
      else
        format.html { render :edit }
        format.json { render json: @programa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programas/1
  # DELETE /programas/1.json
  def destroy
    @programa.destroy
    respond_to do |format|
      format.html { redirect_to programas_url, notice: 'Programa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_programa
      @programa = Programa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def programa_params
      params.require(:programa).permit(:titulo, :descripcion)
    end
end

app/app/helpers/programas_helper.rb
module ProgramasHelper
end

app/app/views/programas/_form.html.erb
<%= simple_form_for(@programa) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :titulo %>
    <%= f.input :descripcion %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/app/views/programas/edit.html.erb
<% if user_signed_in? %>
<h1>Editing Programa</h1>

<%= render 'form', programa: @programa %>

<%= link_to 'Show', @programa %> |
<%= link_to 'Back', programas_path %>
<% end %>

app/app/views/programas/index.html.erb
<% if user_signed_in? %>
<p id="notice"><%= notice %></p>

<h1>Programas</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programas.each do |programa| %>
      <tr>
        <td><%= programa.titulo %></td>
        <td><%= programa.descripcion %></td>
        <td><%= link_to 'Show', programa %></td>
        <td><%= link_to 'Edit', edit_programa_path(programa) %></td>
        <td><%= link_to 'Destroy', programa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Programa', new_programa_path %>
<% end %>

app/app/views/programas/new.html.erb
<% if user_signed_in? %>
<h1>New Programa</h1>

<%= render 'form', programa: @programa %>

<%= link_to 'Back', programas_path %>
<% end %>

app/app/views/programas/show.html.erb
<div class="container">
    <div class="programasSociales">
        <h3> <%= @programa.titulo %></h3>
    </div>
    <div class="row">
        <div class="col l12 m12">
          <div class="carousel carousel-slider" id="carousel-programa" data-indicators="true">
              <% @fotos = Foto.where(programa_id: @programa.id) %>
              <% @fotos.each do |foto|%>
                <%= image_tag foto.imagen.url, class:"carousel-item"%>
              <%end%>
          </div>
        </div>
    </div>
    <div class="col l5 m5">
            <p class="text-programa">
              <%= @programa.descripcion %>
            </p>
        </div>
</div>