app/config/routes.rb
Rails.application.routes.draw do
  resources :ayudas
  resources :categories
  resources :galeria
  resources :fotos
  resources :programas
  resources :eventos
  resources :logos
  resources :carrusels
  resources :programas
  resources :nosotros
  resources :noticias
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 
  get "inicio", to: "pages#inicio"
  
  get "nosotros", to: "pages#nosotros"

  get "programas_sociales", to: "pages#programas"

  get "eventos_noticias", to: "pages#eventos_noticias"

  get "como_ayudar", to: "pages#como_ayudar"

  get "fotos_galeria", to: "pages#galeria"
  
  get "factura", to: 'facturas#new', as: 'new_factura'
  
  post "factura", to: 'facturas#create', as: 'create_factura'
  
  get 'contacto', to: 'contactos#new', as: 'new_contacto'
  post 'contacto', to: 'contactos#create', as: 'create_contacto'
  
  root 'pages#inicio'

  devise_for :users, controllers: {
      sessions: 'devise/sessions',
      passwords: 'devise/passwords',
      registrations: 'devise/registrations'
  }

end

app/app/models/logo.rb
class Logo < ApplicationRecord
    mount_uploader :imagen, ImageUploader
end

app/app/controllers/logos_controller.rb
class LogosController < ApplicationController
  before_action :set_logo, only: [:show, :edit, :update, :destroy]

  # GET /logos
  # GET /logos.json
  def index
    @logos = Logo.all
  end

  # GET /logos/1
  # GET /logos/1.json
  def show
  end

  # GET /logos/new
  def new
    @logo = Logo.new
  end

  # GET /logos/1/edit
  def edit
  end

  # POST /logos
  # POST /logos.json
  def create
    @logo = Logo.new(logo_params)

    respond_to do |format|
      if @logo.save
        format.html { redirect_to @logo, notice: 'Logo was successfully created.' }
        format.json { render :show, status: :created, location: @logo }
      else
        format.html { render :new }
        format.json { render json: @logo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logos/1
  # PATCH/PUT /logos/1.json
  def update
    respond_to do |format|
      if @logo.update(logo_params)
        format.html { redirect_to @logo, notice: 'Logo was successfully updated.' }
        format.json { render :show, status: :ok, location: @logo }
      else
        format.html { render :edit }
        format.json { render json: @logo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logos/1
  # DELETE /logos/1.json
  def destroy
    @logo.destroy
    respond_to do |format|
      format.html { redirect_to logos_url, notice: 'Logo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_logo
      @logo = Logo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def logo_params
      params.require(:logo).permit(:nombre, :imagen)
    end
end

app/app/helpers/logos_helper.rb
module LogosHelper
end

app/app/views/logos/_form.html.erb
<%= simple_form_for(@logo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
    <%= f.input :imagen %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/app/views/logos/edit.html.erb
<% if user_signed_in? %>
<h1>Editing Logo</h1>

<%= render 'form', logo: @logo %>

<%= link_to 'Show', @logo %> |
<%= link_to 'Back', logos_path %>
<% end %>

app/app/views/logos/index.html.erb
<% if user_signed_in? %>
<p id="notice"><%= notice %></p>

<h1>Logos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Imagen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logos.each do |logo| %>
      <tr>
        <td><%= logo.nombre %></td>
        <td><%= logo.imagen %></td>
        <td><%= link_to 'Show', logo %></td>
        <td><%= link_to 'Edit', edit_logo_path(logo) %></td>
        <td><%= link_to 'Destroy', logo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Logo', new_logo_path %>
<% end %>

app/app/views/logos/new.html.erb
<% if user_signed_in? %>
<h1>New Logo</h1>

<%= render 'form', logo: @logo %>

<%= link_to 'Back', logos_path %>
<% end %>

app/app/views/logos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @logo.nombre %>
</p>

<p>
  <strong>Imagen:</strong>
  <%= @logo.imagen %>
</p>

<%= link_to 'Edit', edit_logo_path(@logo) %> |
<%= link_to 'Back', logos_path %>