app/config/routes.rb
Rails.application.routes.draw do
  resources :ayudas
  resources :categories
  resources :galeria
  resources :fotos
  resources :programas
  resources :eventos
  resources :logos
  resources :carrusels
  resources :programas
  resources :nosotros
  resources :noticias
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 
  get "inicio", to: "pages#inicio"
  
  get "nosotros", to: "pages#nosotros"

  get "programas_sociales", to: "pages#programas"

  get "eventos_noticias", to: "pages#eventos_noticias"

  get "como_ayudar", to: "pages#como_ayudar"

  get "fotos_galeria", to: "pages#galeria"
  
  get "factura", to: 'facturas#new', as: 'new_factura'
  
  post "factura", to: 'facturas#create', as: 'create_factura'
  
  get 'contacto', to: 'contactos#new', as: 'new_contacto'
  post 'contacto', to: 'contactos#create', as: 'create_contacto'
  
  root 'pages#inicio'

  devise_for :users, controllers: {
      sessions: 'devise/sessions',
      passwords: 'devise/passwords',
      registrations: 'devise/registrations'
  }

end

app/app/models/ayuda.rb
class Ayuda < ApplicationRecord
    belongs_to :category
    
    mount_uploader :imagen, ImageUploader
    
    validates :nombre, presence: true
    validates :descripcion, presence: true
    validates :imagen, presence: true
    
    def name
        nombre
    end
end

app/app/controllers/ayudas_controller.rb
class AyudasController < ApplicationController
  before_action :set_ayuda, only: [:show, :edit, :update, :destroy]

  # GET /ayudas
  # GET /ayudas.json
  def index
    @ayudas = Ayuda.all
  end

  # GET /ayudas/1
  # GET /ayudas/1.json
  def show
  end

  # GET /ayudas/new
  def new
    @ayuda = Ayuda.new
  end

  # GET /ayudas/1/edit
  def edit
  end

  # POST /ayudas
  # POST /ayudas.json
  def create
    @ayuda = Ayuda.new(ayuda_params)

    respond_to do |format|
      if @ayuda.save
        format.html { redirect_to @ayuda, notice: 'Ayuda was successfully created.' }
        format.json { render :show, status: :created, location: @ayuda }
      else
        format.html { render :new }
        format.json { render json: @ayuda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ayudas/1
  # PATCH/PUT /ayudas/1.json
  def update
    respond_to do |format|
      if @ayuda.update(ayuda_params)
        format.html { redirect_to @ayuda, notice: 'Ayuda was successfully updated.' }
        format.json { render :show, status: :ok, location: @ayuda }
      else
        format.html { render :edit }
        format.json { render json: @ayuda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ayudas/1
  # DELETE /ayudas/1.json
  def destroy
    @ayuda.destroy
    respond_to do |format|
      format.html { redirect_to ayudas_url, notice: 'Ayuda was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ayuda
      @ayuda = Ayuda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ayuda_params
      params.require(:ayuda).permit(:nombre, :descripcion, :imagen, :category_id)
    end
end

app/app/helpers/ayudas_helper.rb
module AyudasHelper
end

app/app/views/ayudas/_form.html.erb
<%= simple_form_for(@ayuda) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
    <%= f.input :descripcion %>
    <%= f.input :imagen %>
    <%= f.input :category_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/app/views/ayudas/edit.html.erb
<% if user_signed_in? %>
<h1>Editing Ayuda</h1>

<%= render 'form', ayuda: @ayuda %>

<%= link_to 'Show', @ayuda %> |
<%= link_to 'Back', ayudas_path %>

<% end %>

app/app/views/ayudas/index.html.erb
<% if user_signed_in? %>
 
        <p id="notice"><%= notice %></p>

<h1>Ayudas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Imagen</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ayudas.each do |ayuda| %>
      <tr>
        <td><%= ayuda.nombre %></td>
        <td><%= ayuda.descripcion %></td>
        <td><%= ayuda.imagen %></td>
        <td><%= ayuda.category_id %></td>
        <td><%= link_to 'Show', ayuda %></td>
        <td><%= link_to 'Edit', edit_ayuda_path(ayuda) %></td>
        <td><%= link_to 'Destroy', ayuda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ayuda', new_ayuda_path %>
 
<% end %>

app/app/views/ayudas/new.html.erb
<% if user_signed_in? %>
<h1>New Ayuda</h1>

<%= render 'form', ayuda: @ayuda %>

<%= link_to 'Back', ayudas_path %>
<% end %>

app/app/views/ayudas/show.html.erb
<div class="container">
  <h4> <%= @ayuda.nombre %> </h4>
  <div class="row">
    <div class="col s4">
      <%= image_tag (@ayuda.imagen), class:"responsive-img" %>
    </div>
    <div class="col s8">
      <p class="ayudas-text"> <%= @ayuda.descripcion %> </p>
    </div>
  </div>
</div>