app/config/routes.rb
Rails.application.routes.draw do
  resources :ayudas
  resources :categories
  resources :galeria
  resources :fotos
  resources :programas
  resources :eventos
  resources :logos
  resources :carrusels
  resources :programas
  resources :nosotros
  resources :noticias
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 
  get "inicio", to: "pages#inicio"
  
  get "nosotros", to: "pages#nosotros"

  get "programas_sociales", to: "pages#programas"

  get "eventos_noticias", to: "pages#eventos_noticias"

  get "como_ayudar", to: "pages#como_ayudar"

  get "fotos_galeria", to: "pages#galeria"
  
  get "factura", to: 'facturas#new', as: 'new_factura'
  
  post "factura", to: 'facturas#create', as: 'create_factura'
  
  get 'contacto', to: 'contactos#new', as: 'new_contacto'
  post 'contacto', to: 'contactos#create', as: 'create_contacto'
  
  root 'pages#inicio'

  devise_for :users, controllers: {
      sessions: 'devise/sessions',
      passwords: 'devise/passwords',
      registrations: 'devise/registrations'
  }

end

app/app/models/noticia.rb
class Noticia < ApplicationRecord
    mount_uploader :imagen, ImageUploader 
    
    validates :titulo, presence: true, allow_blank: false
    validates :descripcion, presence: true, allow_blank: false
    validates :imagen, presence: true,  length: {minimum: 5}, allow_blank: false

end

app/app/controllers/noticias_controller.rb
class NoticiasController < ApplicationController
  before_action :set_noticia, only: [:show, :edit, :update, :destroy]

  # GET /noticias
  # GET /noticias.json
  def index
    @noticias = Noticia.all
  end

  # GET /noticias/1
  # GET /noticias/1.json
  def show
    @noticias_recientes = Noticia.order(created_at: :desc).last(4)
  end

  # GET /noticias/new
  def new
    @noticia = Noticia.new
  end

  # GET /noticias/1/edit
  def edit
  end

  # POST /noticias
  # POST /noticias.json
  def create
    @noticia = Noticia.new(noticia_params)

    respond_to do |format|
      if @noticia.save
        format.html { redirect_to @noticia, notice: 'La noticia se creó correctamente.' }
        format.json { render :show, status: :created, location: @noticia }
      else
        format.html { render :new }
        format.json { render json: @noticia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /noticias/1
  # PATCH/PUT /noticias/1.json
  def update
    respond_to do |format|
      if @noticia.update(noticia_params)
        format.html { redirect_to @noticia, notice: 'La noticia se actualizó correctamente.' }
        format.json { render :show, status: :ok, location: @noticia }
      else
        format.html { render :edit }
        format.json { render json: @noticia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /noticias/1
  # DELETE /noticias/1.json
  def destroy
    @noticia.destroy
    respond_to do |format|
      format.html { redirect_to noticias_url, notice: 'La noticia se eliminó correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_noticia
      @noticia = Noticia.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def noticia_params
      params.require(:noticia).permit(:titulo, :descripcion, :imagen)
    end
end

app/app/helpers/noticias_helper.rb
module NoticiasHelper
end

app/app/views/noticias/_form.html.erb
<%= form_with(model: noticia, local: true) do |form| %>
  <% if noticia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(noticia.errors.count, "error") %> prohibited this noticia from being saved:</h2>

      <ul>
      <% noticia.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, id: :noticia_titulo %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion, id: :noticia_descripcion %>
  </div>

  <div class="field">
    <% if form.object.imagen? %>
      <%= image_tag form.object.imagen.thumb.url %>
    <% end %>
    <%= form.label :imagen %>
    <%= form.file_field :imagen, id: :noticia_imagen %>
  </div>

  <div class="actions">
    <%= form.button :submit, :class=> "btn btn-primary"%>
  </div>
<% end %>

app/app/views/noticias/edit.html.erb
<% if user_signed_in? %>
<div class="container">
    <h1>Editar noticia</h1>

    <%= render 'form', noticia: @noticia %>
    
    <%= link_to 'Mostrar', @noticia %> |
    <%= link_to 'Regresar', noticias_path %>

</div>
<% end %>

app/app/views/noticias/index.html.erb
<% if user_signed_in? %>
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Noticias</h1>
  
  <table class="striped">
    <thead>
      <tr>
        <th>Titulo</th>
        <th>Fecha de creación</th>
        <th>Descripcion</th>
        <th>Imagen</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @noticias.each do |noticia| %>
        <tr>
          <td><%= noticia.titulo %></td>
          <td><%= noticia.created_at %></td>
          <td id="description-table"><%= noticia.descripcion %></td>
          <td><%= noticia.imagen %></td>
          <!-- Mostrar -->
          <td>
            <%= link_to "Mostrar", noticia %>
          </td>
          <!-- Editar -->
          <td>
            <%= link_to edit_noticia_path(noticia) do %>
              <i class="material-icons">edit</i>
            <% end %>
          </td>
          <!-- Eliminar -->
          <td>
            <%= link_to noticia, method: :delete, data: { confirm: '¿Estás seguro que deseas eliminar esta noticia?' } do %>
              <i class="material-icons">delete</i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'Crear noticia', new_noticia_path %>

  
</div>
<% end %>

app/app/views/noticias/new.html.erb
<% if user_signed_in? %>
<div class="container">
    <h1>Crear noticia</h1>

    <%= render 'form', noticia: @noticia %>
    
    <%= link_to 'Regresar', noticias_path %>

</div>
<% end %>

app/app/views/noticias/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <div class="row">
    <!-- Información de la noticia -->
    <div class="card col m8">
      <h4 class="center-align"><%= @noticia.titulo %></h4>
      <hr class="new-hr">
      
      <div class="center-align">
        <%= image_tag @noticia.imagen.url, class: "responsive-img" unless @noticia.imagen.blank? %>
      </div>
      
      <p class="text-news">
        <%= @noticia.descripcion %>
      </p>
      
      <p class="new-date">
        Publicada: <%= l(@noticia.created_at, format: '%a %d de %B del %Y') %>
      </p>
      
    </div>
    
    <!-- Lista de 4 noticias recientes -->
    <div class="col m4 s12">
      <ul class="collection with-header">
        <li class="collection-header"><h5>Noticias recientes</h5></li>
        <% @noticias_recientes.each do |noticia| %>
          <%= link_to noticia, class: 'recent-news' do %>
            <li class="collection-item avatar">
              <%= image_tag noticia.imagen.url, class: "circle" %>
              <span class="title"><%= noticia.titulo %></span>
              <p class="truncate"><%= noticia.descripcion %></p>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>

</div>